version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_APP_ENV=dev
      - NEXT_PUBLIC_API_BASE_URL=http://host.docker.internal:3001
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    networks:
      - vitefait-network

networks:
  vitefait-network:
    driver: bridge 